version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: livestream_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: livestream_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: livestream_redis
    restart: unless-stopped
    ports:
      - "6380:6379"

volumes:
  postgres_data: