export enum FreezeReason {
  FRAUD_SUSPICION = 'FRAUD_SUSPICION',
  CHARGEBACK_RISK = 'CHARGEBACK_RISK',
  ADMIN_DISPUTE = 'ADMIN_DISPUTE',
  SECURITY_HOLD = 'SECURITY_HOLD',
  COMPLIANCE_REVIEW = 'COMPLIANCE_REVIEW',
  OTHER = 'OTHER',
}
