export enum OnboardingStatus {
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  PROFILE_COMPLETED = 'PROFILE_COMPLETED',
  INTERESTS_SELECTED = 'INTERESTS_SELECTED',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  READY = 'READY',
}
