export enum TransactionType {
  COIN_PURCHASE = 'COIN_PURCHASE',
  GIFT_SEND = 'GIFT_SEND',
  CREATOR_EARNING = 'CREATOR_EARNING',
  WITHDRAWAL = 'WITHDRAWAL',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
  REFUND = 'REFUND',
  CHARGEBACK = 'CHARGEBACK',
  PROMO_BONUS = 'PROMO_BONUS',
  REFERRAL_REWARD = 'REFERRAL_REWARD',
  SUBSCRIPTION_PAYMENT = 'SUBSCRIPTION_PAYMENT',
  PENALTY = 'PENALTY',
}
